In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.linear_model import LogisticRegression
model=LogisticRegression(solver='liblinear')

用iris資料集做預測

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
iris=load_iris()

df=pd.DataFrame(iris['data'],columns=iris['feature_names'])
df['target']=iris['target']

df=df[['sepal length (cm)','petal length (cm)','target']]
df=df.iloc[50:]
df.head()

sepal length (cm)  petal length (cm)  target
50                7.0                4.7       1
51                6.4                4.5       1
52                6.9                4.9       1
53                5.5                4.0       1
54                6.5                4.6       1

In [14]:
x_cols=['sepal length (cm)','petal length (cm)']
y_col='target'
x=df[x_cols]
y=df[y_col]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

In [15]:
len(x_train),len(x_test)

(67, 33)

In [16]:
model.fit(x_train,y_train)

LogisticRegression(solver='liblinear')

In [17]:
model.coef_

array([[-1.95087964,  2.76151177]])

In [19]:
y_pred=model.predict(x_test)
y_pred[:5]

array([2, 2, 2, 1, 1])

In [20]:
y_test[:5]

133    2
103    2
120    2
95     1
94     1
Name: target, dtype: int32

In [40]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
pd.DataFrame(cm,columns=['pred_0','pred_1'],index=['true_0','true_1'])

pred_0  pred_1
true_0      16       3
true_1       1      13

In [23]:
accuracy_score(y_test,y_pred)

0.8787878787878788

In [24]:
model.score(x_test,y_test)

0.8787878787878788

用自行設計資料集進行訓練

In [37]:
x_train2_1=[167,175,154,171,181,164]#身高
x_train2_2=[57,67,52,42,71,54]#體重
x_train2=np.array([x_train2_1,x_train2_2])
x_train2,x_train2.T#與一般regression一樣，需要轉成每個欄位為特徵

(array([[167, 175, 154, 171, 181, 164],
        [ 57,  67,  52,  42,  71,  54]]),
 array([[167,  57],
        [175,  67],
        [154,  52],
        [171,  42],
        [181,  71],
        [164,  54]]))

In [38]:
y_train2=np.array([1,1,0,0,1,0])#是否有另一半(1:有,0:沒有)
y_train2

array([1, 1, 0, 0, 1, 0])

In [44]:
model2=LogisticRegression(solver='liblinear')
model2.fit(x_train2.T,y_train2)

LogisticRegression(solver='liblinear')

In [47]:
news=np.array([[175,59],[181,65],[170,50],[167,52],[159,48],[174,55]])
news_test=[1,0,1,0,0,1]
#[175,59]:1,[181,65]:0,[170,50]:1,[167,52]:0,[159,48]:0,[174,55]:1
model2.predict(news)

array([0, 1, 0, 0, 0, 0])

In [48]:
cm=confusion_matrix(news_test,model2.predict(news))
pd.DataFrame(cm,columns=['pred_0','pred_1'],index=['true_0','true_1'])

pred_0  pred_1
true_0       2       1
true_1       3       0

In [49]:
accuracy_score(news_test,model2.predict(news))

0.3333333333333333

In [50]:
model2.score(news,news_test)

0.3333333333333333